import Provider from "@/lib/context/provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cloud | Remenex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Link href="/" className="flex m-4 items-center absolute">
          <Image
            width={50}
            height={50}
            src="/images/logo-transparent.svg"
            alt="logo"
          />
        </Link>
        <Toaster position="top-center" richColors />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
